# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

oc_advert_view:
    path: /advert/view/{id}
    requirements:
        id: '\d+'
    controller: App\Controller\AdvertController::view

oc_advert_add:
    path: /advert/add
    controller: App\Controller\AdvertController::add

oc_advert_edit:
    path: /advert/edit/{id}
    requirements:
        id: '\d+'
    controller: App\Controller\AdvertController::edit

oc_advert_delete:
    path: /advert/delete/{id}
    requirements:
        id: '\d+'
    controller: App\Controller\AdvertController::delete

login:
    path: /login
    defaults:
        _controller: App\Controller\UsersController::login

login_check:
    path: /login_check

logout:
    path: /logout