<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA1zrxc9\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA1zrxc9/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerA1zrxc9.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerA1zrxc9\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerA1zrxc9\srcDevDebugProjectContainer([
    'container.build_hash' => 'A1zrxc9',
    'container.build_id' => '76f784d1',
    'container.build_time' => 1587638920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA1zrxc9');
