<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRp5sr4y\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRp5sr4y/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRp5sr4y.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRp5sr4y\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRp5sr4y\srcDevDebugProjectContainer([
    'container.build_hash' => 'Rp5sr4y',
    'container.build_id' => 'dc686e15',
    'container.build_time' => 1587823277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRp5sr4y');
